version: '3.8'

services:
  app:
    container_name: myvolume
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
     - ./src:/src
    
  database:
    container_name: postgresql
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "example"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres_data: